export const REVIEW_POPOVER_EDGE_MARGIN = 12;
export const REVIEW_POPOVER_DRAWER_WIDTH = "clamp(320px, 34vw, 460px)";
export const REVIEW_POPOVER_DRAWER_OFFSET = `calc(${REVIEW_POPOVER_DRAWER_WIDTH} + ${REVIEW_POPOVER_EDGE_MARGIN}px)`;
